import { z } from "zod";

export const PropertySchema = z.object({
  id: z.string().uuid().optional(), // generated by DB if not provided
  name: z.string().min(1),
  description: z.string().nullable().optional(),
  address: z.string().nullable().optional(),
  city: z.string().nullable().optional(),
  state: z.string().nullable().optional(),
  postalCode: z.string().nullable().optional(),
  streetName : z.string().nullable().default("streetname"),
  streetNumber : z.number().nullable().default(10),
  suburb : z.string().nullable().default("suburb"),
  country: z.string().default("South Africa"),
  type: z.enum([
    "house",
    "apartment",
    "townhouse",
    "condo",
    "duplex",
    "commercial",
    "land",
  ]).default("house"),
  bedrooms: z.number().int().nonnegative().default(0),
  bathrooms: z.number().int().nonnegative().default(0),
  squareFeet: z.number().nullable().optional(),
  hasParking: z.boolean().default(false),
  isFurnished: z.boolean().default(false),
  ownerId: z.string().uuid(),
  price: z.number().nonnegative().nullable().optional(),
  isForRent: z.boolean().default(true),
  isForSale: z.boolean().default(false),
  mainImage: z.string().nullable().optional(),
  images: z.array(z.string()).default([]),
  isActive: z.boolean().default(true),
  createdAt: z.string().datetime().optional(),
  updatedAt: z.string().datetime().nullable().optional(),
});

export type Property = z.infer<typeof PropertySchema>;