import type { Metadata } from "next";
import { Geist_Mono, Karla, Lexend_Deca, Silkscreen } from "next/font/google";
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

const silkScreen = Lexend_Deca({
  subsets : ['latin'],
  weight : '400'
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${silkScreen.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
